# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
recipe: default.v1

language: ja

pipeline:
  - name: SpacyNLP
    model: 'ja_core_news_lg'
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: SpacyEntityExtractor
#  - name: RegexFeaturizer
#  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 2
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100  
  - name: FallbackClassifier
    threshold: .97

policies:
  - name: MemoizationPolicy
  - name: RulePolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
